[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_URL = "https://employee-backend-kn4z.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200